## Authentication Settings
appId: INSERT-ID-HERE
appSecret: INSERT-APP-SECRET-HERE
broadcasterId: INSERT-BROADCASTER-ID
oauthToken: INSERT-OAUTH-TOKEN-HERE

## Which port should the application use?
port: 8000

## Use Ngrok if you are using this in a local machine.
useNgrok: true

## Not used if Ngrok is enabled.
callbackUrl: https://example.com

## Game Settings
games:
  overwatch:
    name: Overwatch 2
    rewards:
      'chooseSkin':
        title: Choose my Skin
        skipRequestQueue: false
        prompt: Choose my Moira skin for the next game!
        userInputRequired: true
        cost: 1000
